CREATE DATABASE IF NOT EXISTS `TODO_List` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `TODO_List`;

CREATE TABLE IF NOT EXISTS `List` (
    `task` varchar(255) NOT NULL,
    `deadline` varchar(255) NOT NULL,
    `complete` BOOLEAN NOT NULL,
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`id`)
) ENGINE InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;